version: "3.7"

services:
  db:
    image: postgres:12.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db
  django_gunicorn:
    build:
      context: .
    ports:
    - "8000:8000"
    env_file:
      - .env
    volumes:
    - static:/static
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  nginx:
    build:
      context: ./nginx
    ports:
    - "80:80"
    volumes:
    - static:/static
    depends_on:
      - django_gunicorn

volumes:
  static:
  postgres_data:
