version: "3.7"

services:
  django_gunicorn:
    build:
      context: .
    ports:
    - "8000:8000"
    env_file:
      - .env
    volumes:
    - static:/static

  nginx:
    build:
      context: ./nginx
    ports:
    - "80:80"
    volumes:
    - static:/static
    depends_on:
      - django_gunicorn

volumes:
  static:
